# Generated by Django 4.2.5 on 2023-09-10 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_user_id_alter_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Admin', 'Admin')], default='Customer', max_length=20),
        ),
    ]
