# Generated by Django 4.2.5 on 2023-09-10 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_shippingaddress_user_addr_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
    ]
