# Generated by Django 4.2.5 on 2023-09-10 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Quantity',
            new_name='quantity',
        ),
    ]
